import qcetl.common
from qcetl.column import (
    UmiQcColumn,
    UmiQcExtractionColumn,
    UmiQcFamilyColumn,
    UmiQcBamQcColumn,
)
from qcetl.umiqc.parse import parse_record


class umiQcCache(qcetl.common.Cache):
    def __init__(self):
        self.name = "umiqc"
        self.schema_versions = {
            2: {
                "umiqc_metrics": {
                    UmiQcColumn.Barcodes: "s",
                    UmiQcColumn.Lane: "i",
                    UmiQcColumn.Run: "s",
                    UmiQcColumn.FileSWID: "s",
                    UmiQcColumn.PreDedupTotalReads: "i",
                    UmiQcColumn.PreDedupMappedReads: "i",
                    UmiQcColumn.PostDedupTotalReads: "i",
                    UmiQcColumn.PostDedupMappedReads: "i",
                    UmiQcColumn.PreDedupMeanDepth: "f",
                    UmiQcColumn.PostDedupMeanDepth: "f",
                    UmiQcColumn.PreDedupDepthSD: "f",
                    UmiQcColumn.PostDedupDepthSD: "f",
                    UmiQcColumn.TotalFamilies: "i",
                    UmiQcColumn.TotalUmiCount: "i",
                },
                "pre_dedup_bam_metrics": {
                    UmiQcColumn.Barcodes: "s",
                    UmiQcColumn.Lane: "i",
                    UmiQcColumn.Run: "s",
                    UmiQcColumn.FileSWID: "s",
                    UmiQcBamQcColumn.AlignedReference: "p",
                    UmiQcBamQcColumn.AverageReadLength: "f",
                    UmiQcBamQcColumn.BasesMapped: "i",
                    UmiQcBamQcColumn.Coverage: "f",
                    UmiQcBamQcColumn.CoverageDeduplicated: "f",
                    UmiQcBamQcColumn.CoverageMedian: "qf",
                    UmiQcBamQcColumn.CoverageMedian10Percentile: "qi",
                    UmiQcBamQcColumn.CoverageMedian90Percentile: "qi",
                    UmiQcBamQcColumn.DeletedBases: "i",
                    UmiQcBamQcColumn.DownsampledTotal: "qi",
                    UmiQcBamQcColumn.HardClipBases: "i",
                    UmiQcBamQcColumn.InsertMax: "i",
                    UmiQcBamQcColumn.InsertMean: "f",
                    UmiQcBamQcColumn.InsertMedian: "f",
                    UmiQcBamQcColumn.InsertSD: "f",
                    UmiQcBamQcColumn.InsertCount: "i",
                    UmiQcBamQcColumn.Insert10Percentile: "qi",
                    UmiQcBamQcColumn.Insert90Percentile: "qi",
                    UmiQcBamQcColumn.LowQualityReadsMeta: "i",
                    UmiQcBamQcColumn.MappedReads: "i",
                    UmiQcBamQcColumn.MarkDuplicates_ESTIMATED_LIBRARY_SIZE: "qi",
                    UmiQcBamQcColumn.MarkDuplicates_LIBRARY: "qs",
                    UmiQcBamQcColumn.MarkDuplicates_PERCENT_DUPLICATION: "qf",
                    UmiQcBamQcColumn.MarkDuplicates_READ_PAIR_DUPLICATES: "qi",
                    UmiQcBamQcColumn.MarkDuplicates_READ_PAIR_OPTICAL_DUPLICATES: "qi",
                    UmiQcBamQcColumn.MarkDuplicates_READ_PAIRS_EXAMINED: "qi",
                    UmiQcBamQcColumn.MarkDuplicates_UNMAPPED_READS: "qi",
                    UmiQcBamQcColumn.MarkDuplicates_UNPAIRED_READ_DUPLICATES: "qi",
                    UmiQcBamQcColumn.MarkDuplicates_UNPAIRED_READS_EXAMINED: "qi",
                    UmiQcBamQcColumn.MismatchBases: "i",
                    UmiQcBamQcColumn.NonPrimaryReads: "i",
                    UmiQcBamQcColumn.NonPrimaryReadsMeta: "i",
                    UmiQcBamQcColumn.NumberOfTargets: "i",
                    UmiQcBamQcColumn.PackageVersion: "s",
                    UmiQcBamQcColumn.PairedEnd: "b",
                    UmiQcBamQcColumn.PairedReads: "i",
                    UmiQcBamQcColumn.PairsMappedAbnormallyFar: "i",
                    UmiQcBamQcColumn.PairsMappedToDifferentChr: "i",
                    UmiQcBamQcColumn.ProperlyPairedReads: "i",
                    UmiQcBamQcColumn.QualityCutoff: "qf",
                    UmiQcBamQcColumn.QualityFailedReads: "i",
                    UmiQcBamQcColumn.Read1AverageLength: "f",
                    UmiQcBamQcColumn.Read2AverageLength: "f",
                    UmiQcBamQcColumn.ReadsMappedAndPaired: "i",
                    UmiQcBamQcColumn.ReadsOnTarget: "i",
                    UmiQcBamQcColumn.ReadsPerStartPoint: "f",
                    UmiQcBamQcColumn.ReadsMissingMDTags: "i",
                    UmiQcBamQcColumn.Sample: "qs",
                    UmiQcBamQcColumn.SampleLevel: "qi",
                    UmiQcBamQcColumn.SoftClipBases: "i",
                    UmiQcBamQcColumn.TargetFile: "p",
                    UmiQcBamQcColumn.TotalBasesOnTarget: "i",
                    UmiQcBamQcColumn.TotalInputReadsMeta: "i",
                    UmiQcBamQcColumn.TotalClusters: "i",
                    UmiQcBamQcColumn.TotalReads: "i",
                    UmiQcBamQcColumn.TotalTargetSize: "i",
                    UmiQcBamQcColumn.UnmappedReads: "i",
                    UmiQcBamQcColumn.UnmappedReadsMeta: "i",
                    UmiQcBamQcColumn.Reference: "s",
                    UmiQcBamQcColumn.Instrument: "s",
                    UmiQcBamQcColumn.Library: "qs",
                    UmiQcBamQcColumn.WorkflowVersion: "qs",
                },
                "post_dedup_bam_metrics": {
                    UmiQcColumn.Barcodes: "s",
                    UmiQcColumn.Lane: "i",
                    UmiQcColumn.Run: "s",
                    UmiQcColumn.FileSWID: "s",
                    UmiQcBamQcColumn.AlignedReference: "p",
                    UmiQcBamQcColumn.AverageReadLength: "f",
                    UmiQcBamQcColumn.BasesMapped: "i",
                    UmiQcBamQcColumn.Coverage: "f",
                    UmiQcBamQcColumn.CoverageDeduplicated: "f",
                    UmiQcBamQcColumn.CoverageMedian: "qf",
                    UmiQcBamQcColumn.CoverageMedian10Percentile: "qi",
                    UmiQcBamQcColumn.CoverageMedian90Percentile: "qi",
                    UmiQcBamQcColumn.DeletedBases: "i",
                    UmiQcBamQcColumn.DownsampledTotal: "qi",
                    UmiQcBamQcColumn.HardClipBases: "i",
                    UmiQcBamQcColumn.InsertMax: "i",
                    UmiQcBamQcColumn.InsertMean: "f",
                    UmiQcBamQcColumn.InsertMedian: "f",
                    UmiQcBamQcColumn.InsertSD: "f",
                    UmiQcBamQcColumn.InsertCount: "i",
                    UmiQcBamQcColumn.Insert10Percentile: "qi",
                    UmiQcBamQcColumn.Insert90Percentile: "qi",
                    UmiQcBamQcColumn.LowQualityReadsMeta: "i",
                    UmiQcBamQcColumn.MappedReads: "i",
                    UmiQcBamQcColumn.MarkDuplicates_ESTIMATED_LIBRARY_SIZE: "qi",
                    UmiQcBamQcColumn.MarkDuplicates_LIBRARY: "qs",
                    UmiQcBamQcColumn.MarkDuplicates_PERCENT_DUPLICATION: "qf",
                    UmiQcBamQcColumn.MarkDuplicates_READ_PAIR_DUPLICATES: "qi",
                    UmiQcBamQcColumn.MarkDuplicates_READ_PAIR_OPTICAL_DUPLICATES: "qi",
                    UmiQcBamQcColumn.MarkDuplicates_READ_PAIRS_EXAMINED: "qi",
                    UmiQcBamQcColumn.MarkDuplicates_UNMAPPED_READS: "qi",
                    UmiQcBamQcColumn.MarkDuplicates_UNPAIRED_READ_DUPLICATES: "qi",
                    UmiQcBamQcColumn.MarkDuplicates_UNPAIRED_READS_EXAMINED: "qi",
                    UmiQcBamQcColumn.MismatchBases: "i",
                    UmiQcBamQcColumn.NonPrimaryReads: "i",
                    UmiQcBamQcColumn.NonPrimaryReadsMeta: "i",
                    UmiQcBamQcColumn.NumberOfTargets: "i",
                    UmiQcBamQcColumn.PackageVersion: "s",
                    UmiQcBamQcColumn.PairedEnd: "b",
                    UmiQcBamQcColumn.PairedReads: "i",
                    UmiQcBamQcColumn.PairsMappedAbnormallyFar: "i",
                    UmiQcBamQcColumn.PairsMappedToDifferentChr: "i",
                    UmiQcBamQcColumn.ProperlyPairedReads: "i",
                    UmiQcBamQcColumn.QualityCutoff: "qf",
                    UmiQcBamQcColumn.QualityFailedReads: "i",
                    UmiQcBamQcColumn.Read1AverageLength: "f",
                    UmiQcBamQcColumn.Read2AverageLength: "f",
                    UmiQcBamQcColumn.ReadsMappedAndPaired: "i",
                    UmiQcBamQcColumn.ReadsOnTarget: "i",
                    UmiQcBamQcColumn.ReadsPerStartPoint: "f",
                    UmiQcBamQcColumn.ReadsMissingMDTags: "i",
                    UmiQcBamQcColumn.Sample: "qs",
                    UmiQcBamQcColumn.SampleLevel: "qi",
                    UmiQcBamQcColumn.SoftClipBases: "i",
                    UmiQcBamQcColumn.TargetFile: "p",
                    UmiQcBamQcColumn.TotalBasesOnTarget: "i",
                    UmiQcBamQcColumn.TotalInputReadsMeta: "i",
                    UmiQcBamQcColumn.TotalClusters: "i",
                    UmiQcBamQcColumn.TotalReads: "i",
                    UmiQcBamQcColumn.TotalTargetSize: "i",
                    UmiQcBamQcColumn.UnmappedReads: "i",
                    UmiQcBamQcColumn.UnmappedReadsMeta: "i",
                    UmiQcBamQcColumn.Reference: "s",
                    UmiQcBamQcColumn.Instrument: "s",
                    UmiQcBamQcColumn.Library: "qs",
                    UmiQcBamQcColumn.WorkflowVersion: "qs",
                },
                "extraction_metrics": {
                    UmiQcExtractionColumn.Barcodes: "s",
                    UmiQcExtractionColumn.Lane: "i",
                    UmiQcExtractionColumn.Run: "s",
                    UmiQcExtractionColumn.FileSWID: "s",
                    UmiQcExtractionColumn.TotalReadsPairs: "i",
                    UmiQcExtractionColumn.ReadsPairsWithMatchingPattern: "i",
                    UmiQcExtractionColumn.DiscardedReadsPairs: "i",
                    UmiQcExtractionColumn.DiscardedReadsPairsDueToUnknownUMI: "i",
                    UmiQcExtractionColumn.umiListFile: "s",
                    UmiQcExtractionColumn.pattern1: "s",
                    UmiQcExtractionColumn.pattern2: "s",
                },
                "family_size_distribution": {
                    UmiQcFamilyColumn.Barcodes: "s",
                    UmiQcFamilyColumn.Lane: "i",
                    UmiQcFamilyColumn.Run: "s",
                    UmiQcFamilyColumn.FileSWID: "s",
                    UmiQcFamilyColumn.FamilySize: "i",
                    UmiQcFamilyColumn.PreDedupUmiCounts: "i",
                    UmiQcFamilyColumn.PostDedupUmiCounts: "i",
                },
            }
        }
        self.columns = {
            2: {
                "umiqc_metrics": UmiQcColumn,
                "pre_dedup_bam_metrics": UmiQcBamQcColumn,
                "post_dedup_bam_metrics": UmiQcBamQcColumn,
                "extraction_metrics": UmiQcExtractionColumn,
                "family_size_distribution": UmiQcFamilyColumn,
            }
        }
        self.input_format = {
            "pre_dedup_bam_metrics": "p",
            "post_dedup_bam_metrics": "p",
            "extraction_metrics": "p",
            "umiCountsPerPosition": "p",
            "swid": "s",
            "barcodes": "s",
            "lane": "i",
            "run": "s",
            "reference": "s",
        }
        self.primary_key = {
            2: {
                "umiqc_metrics": [
                    UmiQcColumn.Barcodes,
                    UmiQcColumn.Lane,
                    UmiQcColumn.Run,
                ],
                "pre_dedup_bam_metrics": [UmiQcColumn.FileSWID],
                "extraction_metrics": [UmiQcColumn.FileSWID],
                "post_dedup_bam_metrics": [UmiQcColumn.FileSWID],
                "family_size_distribution": [
                    UmiQcFamilyColumn.FamilySize,
                    UmiQcFamilyColumn.Barcodes,
                    UmiQcFamilyColumn.Lane,
                    UmiQcFamilyColumn.Run,
                ],
            }
        }
        self.input_key = {2: ("swid", UmiQcColumn.FileSWID)}

    def parse_single_record(self, single_input, schema_version):
        (
            umiqc_metrics_df,
            pre_dedup_bam_metrics_df,
            post_dedup_bam_metrics_df,
            extraction_metrics_df,
            family_size_distribution_df,
        ) = parse_record(
            single_input["umiCountsPerPosition"],
            single_input["pre_dedup_bam_metrics"],
            single_input["post_dedup_bam_metrics"],
            single_input["extraction_metrics"],
        )

        return {
            2: {
                "umiqc_metrics": umiqc_metrics_df,
                "pre_dedup_bam_metrics": pre_dedup_bam_metrics_df,
                "post_dedup_bam_metrics": post_dedup_bam_metrics_df,
                "extraction_metrics": extraction_metrics_df,
                "family_size_distribution": family_size_distribution_df,
            }
        }[schema_version]

    def add_shesmu_metadata(self, single_input, schema_version):
        return {
            "umiqc_metrics": {
                UmiQcColumn.FileSWID: single_input["swid"],
                UmiQcColumn.Barcodes: single_input["barcodes"],
                UmiQcColumn.Lane: single_input["lane"],
                UmiQcColumn.Run: single_input["run"],
            },
            "pre_dedup_bam_metrics": {
                UmiQcColumn.FileSWID: single_input["swid"],
                UmiQcColumn.Barcodes: single_input["barcodes"],
                UmiQcColumn.Lane: single_input["lane"],
                UmiQcColumn.Run: single_input["run"],
                UmiQcBamQcColumn.Reference: single_input.get(
                    "reference", "Unknown"
                ),
            },
            "post_dedup_bam_metrics": {
                UmiQcColumn.FileSWID: single_input["swid"],
                UmiQcColumn.Barcodes: single_input["barcodes"],
                UmiQcColumn.Lane: single_input["lane"],
                UmiQcColumn.Run: single_input["run"],
                UmiQcBamQcColumn.Reference: single_input.get(
                    "reference", "Unknown"
                ),
            },
            "extraction_metrics": {
                UmiQcColumn.FileSWID: single_input["swid"],
                UmiQcColumn.Barcodes: single_input["barcodes"],
                UmiQcColumn.Lane: single_input["lane"],
                UmiQcColumn.Run: single_input["run"],
            },
            "family_size_distribution": {
                UmiQcColumn.FileSWID: single_input["swid"],
                UmiQcColumn.Barcodes: single_input["barcodes"],
                UmiQcColumn.Lane: single_input["lane"],
                UmiQcColumn.Run: single_input["run"],
            },
        }
