import json
import pandas as pd


def parse_record(path: str) -> pd.DataFrame:
    """

    Args:
        path: path to report file in json format
    Returns:
        DataFrame

    host_reads graft_reads both_reads neither_reads

    Load metrics generated by xenoclassify, report number of reads assigned to different bins
    we may encounter two types of json from xenoclassify (a newer one has a nested structure keyed
    with id for the sequenced lane)

    Examples:

    {"both": "33", "graft": "8842", "neither": "4"}

    or in case of the newer version:

    {
     "220728_M00753_0471_000000000-DGYKY-ACCACGAT-TTGCAGAC_1": {
      "both": "258",
      "host": "30926",
      "neither": "60",
      "graft": "123905"
     }
    }

    the ius in qc-etl system is identified by other means, so we strip it and pass only
    the hash with counts, so that outputs for both versions are in the same format

    """

    with open(path) as data_file:
        data = json.load(data_file)

    """ Check if have a nested json """
    isNested = False
    for key in data.keys():
        if isinstance(data[key], dict):
            isNested = True
            break

    if isNested:
        data_items = list(data.items())
        df = pd.json_normalize(data_items[0][1])
    else:
        df = pd.json_normalize(data)

    """ Construct one-row DataFrame to return """
    data_to_return = {
        "host_reads": int(df["host"].iloc[0]) if "host" in df.keys() else 0,
        "graft_reads": int(df["graft"].iloc[0]) if "graft" in df.keys() else 0,
        "both_reads": int(df["both"].iloc[0]) if "both" in df.keys() else 0,
        "neither_reads": (
            int(df["neither"].iloc[0]) if "neither" in df.keys() else 0
        ),
    }

    return pd.DataFrame(data_to_return, index=[0])
