from enum import Enum

from qcetl.column import BaseColumn


class InstrumentColumn(BaseColumn):
    InstrumentID = "id"
    InstrumentName = "name"
    ModelID = "model_id"


class InstrumentModelColumn(BaseColumn):
    ModelID = "id"
    ModelName = "name"
    Platform = "platform"


class InstrumentWithModelColumn(BaseColumn):
    InstrumentID = "id_instrument"
    InstrumentName = "name_instrument"
    ModelID = "id_model"
    ModelName = "name_model"
    Platform = "platform"


class LaneProvenanceColumn(BaseColumn):
    CreateDate = "createdDate"
    RunIDandPosition = "geo_run_id_and_position"
    InstrumentName = "instrument_name"
    LaneNumber = "laneNumber"
    LastModified = "lastModified"
    PoolName = "pool_name"
    RunBaseMask = "run_bases_mask"
    RunDir = "run_dir"
    SampleName = "sampleName"
    SampleProvenanceID = "sampleProvenanceId"
    SequencerRunName = "sequencerRunName"
    SequencerRunPlatformModel = "sequencerRunPlatformModel"
    SequencingParameters = "sequencing_parameters"
    Skip = "skip"
    Version = "version"
    WorkflowType = "workflow_type"


class ProjectsColumn(BaseColumn):
    ArchivedSampleCount = "archived_count"
    IsClinical = "clinical"
    EarliestSampleDate = "earliest"
    IsActive = "active"
    LatestSampleData = "latest"
    Name = "name"
    Samplecount = "count"


class SampleProvenanceColumn(BaseColumn):
    CreateDate = "createdDate"
    DV200 = "dv200"
    ExternalName = "geo_external_name"
    GroupID = "geo_group_id"
    GroupIDDescription = "geo_group_id_description"
    LibrarySourceTemplateType = "geo_library_source_template_type"
    NanodropConcentration = "geo_nanodrop_concentration"
    Organism = "geo_organism"
    PrepKit = "geo_prep_kit"
    Purpose = "geo_purpose"
    QubitConcentration = "geo_qubit_concentration"
    ReceiveDate = "geo_receive_date"
    RunIDandPosition = "geo_run_id_and_position"
    STRResult = "geo_str_result"
    TargetedResequencing = "geo_targeted_resequencing"
    TemplateType = "geo_template_type"
    TissueOrigin = "geo_tissue_origin"
    TissuePreparation = "geo_tissue_preparation"
    TissueRegion = "geo_tissue_region"
    TissueType = "geo_tissue_type"
    TubeID = "geo_tube_id"
    Institute = "institute"
    InstrumentName = "instrument_name"
    IUSTag = "iusTag"
    LaneNumber = "laneNumber"
    LastModified = "lastModified"
    ParentSampleName = "parentSampleName"
    PoolName = "pool_name"
    RIN = "rin"
    RootSampleName = "rootSampleName"
    RunBaseMask = "run_bases_mask"
    RunDir = "run_dir"
    SampleName = "sampleName"
    SampleProvenanceID = "sampleProvenanceId"
    SequencerRunName = "sequencerRunName"
    SequencerRunPlatformModel = "sequencerRunPlatformModel"
    SequencingControlType = "sequencing_control_type"
    SequencingParameters = "sequencing_parameters"
    Skip = "skip"
    StudyTitle = "studyTitle"
    SubProject = "subproject"
    UMIs = "umis"
    Version = "version"
    WorkflowType = "workflow_type"


class SampleCategory(Enum):
    Identity = "Identity"
    Stock = "Stock"
    Tissue = "Tissue"
    Aliquot = "Aliquot"
    TissueProcessing = "Tissue Processing"


class HeredityColumn:
    HeredityID = "heredity id"


class HeredityIndex:
    ID = "id"
    Type = "type"


class SamplesColumn:
    Archived = "archived"
    Barcode = "Barcode"
    BarcodeTwo = "Barcode Two"
    CellViability = "Cell Viability"
    Concentration = "concentration"
    CreatedByID = "created_by_id"
    CreatedByURL = "created_by_url"
    CreatedDate = "created_date"
    Description = "description"
    Discards = "Discards"
    Distributed = "Distributed"
    DistributionDate = "Distribution Date"
    DV200 = "DV200"
    ExternalName = "External Name"
    GroupDescription = "Group Description"
    ID = "id"
    GroupID = "Group ID"
    InitialVolume = "Initial Volume"
    InLabCreationDate = "In-lab Creation Date"
    Institute = "Institute"
    MarkedAreaSize = "Marked Area (mm²)"
    MarkedAreaPercentTumour = "Marked Area Percent Tumour"
    ModifiedByID = "modified_by_id"
    ModifiedByURL = "modified_by_url"
    ModifiedDate = "modified_date"
    Name = "name"
    NanodropConcentration = "Nanodrop (ng/uL)"
    Organism = "Organism"
    PercentNecrosis = "Percent Necrosis"
    PercentTumour = "Percent Tumour"
    PreparationKitDescription = "preparation_kit_description"
    PreparationKitName = "preparation_kit_name"
    ProjectName = "project_name"
    Purpose = "Purpose"
    QubitConcentration = "Qubit (ng/uL)"
    ReadLength = "Read Length"
    ReceiveDate = "Receive Date"
    ReferenceSlide = "Reference Slide"
    Region = "Region"
    RIN = "RIN"
    SampleCategory = "Sample Category"
    SampleType = "sample_type"
    Sex = "Sex"
    Slides = "Slides"
    SlidesConsumed = "Slides Consumed"
    SourceTemplateType = "Source Template Type"
    SpikeIn = "Spike-In"
    SpikeInDilutionFactor = "Spike-In Dilution Factor"
    SpikeInVolume = "Spike-In-Volume (uL)"
    Stain = "Stain"
    State = "state"
    Status = "status"
    StorageLocation = "storage_location"
    STR = "STR"
    SubProject = "Sub-project"
    Synthetic = "Synthetic"
    TargetCellRecovery = "Target Cell Recovery"
    TargetedResequencing = "Targeted Resequencing"
    TissueOrigin = "Tissue Origin"
    TissuePreparation = "Tissue Preparation"
    TissueType = "Tissue Type"
    TissueID = "Tube Id"
    TubeBarcode = "tube_barcode"
    URL = "url"
    Volume = "volume"


class SamplesIndex:
    ID = "id"


class PoolsColumn:
    Barcode = "barcode"
    BarcodeTwo = "barcode_two"
    ID = "id"
    PoolCreatedByID = "pool_created_by_id"
    PoolCreatedDate = "pool_created_date"
    PoolDescription = "pool_description"
    PoolName = "pool_name"
    Position = "position"
    RunAlias = "run_alias"
    URL = "url"
    TargetedResequencing = "Targeted Resequencing"


class RunsColumn:
    Barcode = "barcode"
    CompletionDate = "completion_date"
    CreatedByID = "created_by_id"
    CreatedByURL = "created_by_url"
    CreatedDate = "created_date"
    ID = "id"
    InstrumentID = "instrument_id"
    InstrumentURL = "instrument_url"
    ModifiedByID = "modified_by_id"
    ModifiedByURL = "modified_by_url"
    ModifiedDate = "modified_date"
    Name = "name"
    RunBasesMask = "run_bases_mask"
    RunDirectory = "run_directory"
    SequencingParameters = "sequencing_parameters"
    StartDate = "start_date"
    State = "state"
    URL = "url"
    WorkflowType = "workflow_type"
