name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Sync environment
        run: uv sync --frozen

      - name: Run pre-commit checks
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest -o console_output_style=none
